spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      show_sql: false
      format_sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paypal_db
    schema: public
    username: postgres
    password: user